behaviors:
  3DGameKitDefault:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.03
      learning_rate_schedule: linear
      batch_size: 128
      buffer_size: 5000
      buffer_init_steps: 1000
      tau: 0.01
      steps_per_update: 10.0
      save_replay_buffer: false
      init_entcoef: 0.01
      reward_signal_steps_per_update: 10.0
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 4
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 2.0
      gail:
        gamma: 0.99
        strength: 0.1
        learning_rate: 0.0003
        use_actions: true
        use_vail: false
        demo_path: Assets/Demonstrations/3DGameKitDefault.demo
    keep_checkpoints: 5
    max_steps: 3000000
    time_horizon: 128
    summary_freq: 30000
    exploration:
      epsilon_schedule:
        initial_epsilon: 1.0
        final_epsilon: 0.1
        epsilon_decay_steps: 1000000