behaviors:
  3DGameKitDefault:
    trainer_type: ppo
    hyperparameters:
      learning_rate: 0.003
      learning_rate_schedule: linear
      batch_size: 256
      buffer_size: 10240
      epsilon: 0.2
      beta: 0.001
      lambd: 0.95
      num_epoch: 3
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 4
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 2.0
      gail:
        gamma: 0.99
        strength: 0.01
        learning_rate: 0.0003
        use_actions: true
        use_vail: false
        demo_path: Demonstrations/
    keep_checkpoints: 5
    max_steps: 9000000
    time_horizon: 2048
    summary_freq: 30000